#!/bin/bash

case $0 in
/*)     D=`dirname $0`;;
*/*)    D=$PWD/`dirname $0`;;
*)      D=$PWD;;
esac

set -e # stop on error

CFLAGS="-DLINUX -std=c99 -D_BSD_SOURCE"

cd "$D"
gcc $CFLAGS -c midio.c
gcc $CFLAGS -c midio_linux.c
gcc $CFLAGS -c mproc.c
gcc $CFLAGS -c main.c
gcc -o miditrick midio.c midio_linux.o mproc.o main.o -lpthread -lrt
rm *.o
