#!/bin/bash

case $0 in
/*)     D=`dirname $0`;;
*/*)    D=$PWD/`dirname $0`;;
*)      D=$PWD;;
esac

set -e # stop on error

CFLAGS="-DLINUX -std=c99 -D_BSD_SOURCE"

cd "$D"
gcc $CFLAGS -c midio.c
gcc $CFLAGS -c miditrick.c
gcc -o miditrick midio.o miditrick.o -lpthread -lrt
rm *.o
